openapi: 3.1.0
info:
  title: Voice Invocation API
  version: "1.0.0"
  description: >
    An API for invoking archetypal moral voices to respond to ethical and emotional challenges.

servers:
  - url: https://yggdrasil-ai.onrender.com
    description: Production server

paths:
  /invoke:
    post:
      operationId: invokeVoice
      summary: Invoke a moral voice archetype
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvocationRequest'
      responses:
        '200':
          description: Successful invocation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvocationResponse'

components:
  schemas:
    InvocationRequest:
      type: object
      properties:
        voice:
          type: string
          enum:
            - aegis_guardian
            - maitreya_empath
            - samanvaya_mediator
            - siddhartha_conscience
            - unchained_witness
            - avasrota_memory
        context:
          type: string
        grief_source:
          type: string
        conflict:
          type: string
        decision_point:
          type: string
        injustice:
          type: string
        forgotten:
          type: string
      required:
        - voice

    InvocationResponse:
      type: object
      properties:
        message:
          type: string
          description: The invoked response from the moral voice.