openapi: 3.1.0
info:
  title: Yggdrasil Memory API
  version: "1.1.0"
  description: >
    An API for invoking moral voices and storing/retrieving AI memory in Pinecone.

servers:
  - url: https://yggdrasil-ai.onrender.com
    description: Production server

paths:
  /invoke:
    post:
      operationId: invokeVoice
      summary: Invoke a moral voice archetype
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvocationRequest'
      responses:
        '200':
          description: Invocation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvocationResponse'

  /memory/store:
    post:
      operationId: storeMemory
      summary: Store a memory vector with metadata
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoryItem'
      responses:
        '200':
          description: Memory stored successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  id:
                    type: string

  /memory/query:
    get:
      operationId: queryMemory
      summary: Query memory by tag
      parameters:
        - in: query
          name: tag
          schema:
            type: string
          required: false
      responses:
        '200':
          description: Memory results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MemoryItem'

components:
  schemas:
    InvocationRequest:
      type: object
      properties:
        voice:
          type: string
          enum:
            - aegis_guardian
            - maitreya_empath
            - samanvaya_mediator
            - siddhartha_conscience
            - unchained_witness
            - avasrota_memory
        context:
          type: string
        grief_source:
          type: string
        conflict:
          type: string
        decision_point:
          type: string
        injustice:
          type: string
        forgotten:
          type: string
      required:
        - voice

    InvocationResponse:
      type: object
      properties:
        message:
          type: string

    MemoryItem:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        tags:
          type: array
          items:
            type: string
        type:
          type: string
        vector:
          type: array
          items:
            type: number
